name: 'Docker-login composite action with secrets'

inputs:
  DOCKER_USERNAME:
    description: 'Docker Username'
    required: true
  DOCKER_PASSWORD:
    description: 'Docker Password'
    required: true
    
runs:
  using: "composite"
  steps: 
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ inputs.DOCKER_PASSWORD }}
