name: Validate Pull Request on Develop

on:
  pull_request:
    branches: 
      - develop

jobs:
  backend-build:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-rest/
         
    steps:
      - name: Check out repository     
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn test

  frontend-build:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-angular/

    steps:
      - name: Check out repository       
        uses: actions/checkout@v4
        
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: 'npm'
          cache-dependency-path: './00-spring-petclinic-deployment/spring-petclinic-angular/package-lock.json'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build --prod
        
      - name: Test
        run: npm run test-headless
